version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./bookmarks.db:/app/bookmarks.db
